export const MOCK_COURTS = [
    {
      id: "1",
      name: "Sunset Park Basketball Court",
      image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800",
      latitude: 37.7749,
      longitude: -122.4194,
      distance: "0.5 mi",
      playersCount: 8,
      busynessData: [2, 3, 5, 8, 12, 10],
      players: [
        {
          id: "p1",
          name: "Mike Johnson",
          profileImage: "https://ui-avatars.com/api/?name=Mike+Johnson&background=FF6B35&color=fff",
          position: "Point Guard",
          height: "6'0\"",
        },
        {
          id: "p2",
          name: "Sarah Chen",
          profileImage: "https://ui-avatars.com/api/?name=Sarah+Chen&background=FF6B35&color=fff",
          position: "Shooting Guard",
          height: "5'8\"",
        },
      ],
    },
    {
      id: "2",
      name: "Downtown Recreation Center",
      image: "https://images.unsplash.com/photo-1504450758481-7338eba7524a?w=800",
      latitude: 37.7849,
      longitude: -122.4094,
      distance: "1.2 mi",
      playersCount: 12,
      busynessData: [3, 5, 8, 12, 15, 11],
      players: [],
    },
    {
      id: "3",
      name: "Beach Basketball Courts",
      image: "https://images.unsplash.com/photo-1519861531473-9200262188bf?w=800",
      latitude: 37.7649,
      longitude: -122.4294,
      distance: "2.0 mi",
      playersCount: 0,
      busynessData: [1, 2, 3, 5, 8, 6],
      players: [],
    },
    {
      id: "4",
      name: "North Park Courts",
      image: "https://images.unsplash.com/photo-1574623452334-1e0ac2b3ccb4?w=800",
      latitude: 37.7949,
      longitude: -122.3994,
      distance: "2.5 mi",
      playersCount: 4,
      busynessData: [2, 4, 6, 8, 10, 7],
      players: [],
    },
  ];
  
  export const MOCK_PLAYERS = [
    {
      id: "1",
      name: "Alex Thompson",
      profileImage: "https://ui-avatars.com/api/?name=Alex+Thompson&background=FF6B35&color=fff",
      position: "Small Forward",
      height: "6'4\"",
    },
    {
      id: "2",
      name: "Jordan Lee",
      profileImage: "https://ui-avatars.com/api/?name=Jordan+Lee&background=FF6B35&color=fff",
      position: "Center",
      height: "6'8\"",
    },
    {
      id: "3",
      name: "Taylor Martinez",
      profileImage: "https://ui-avatars.com/api/?name=Taylor+Martinez&background=FF6B35&color=fff",
      position: "Point Guard",
      height: "5'10\"",
    },
    {
      id: "4",
      name: "Chris Wilson",
      profileImage: "https://ui-avatars.com/api/?name=Chris+Wilson&background=FF6B35&color=fff",
      position: "Power Forward",
      height: "6'6\"",
    },
    {
      id: "5",
      name: "Morgan Davis",
      profileImage: "https://ui-avatars.com/api/?name=Morgan+Davis&background=FF6B35&color=fff",
      position: "Shooting Guard",
      height: "6'2\"",
    },
  ];